name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit testing
      run: bash ./gradlew build
    - name: Get Apk Version
      uses: JantHsueh/get-apk-info-action@1.0
      with:
        # apk path
        apkPath: app/build/outputs/apk/release/app-release.apk
